### ISSUE TITLE
README changes

### ISSUE THREAD

**Issue by vanegithub** [Gradiant/SI-AI-Data-Ops-PythonBase#1]
Aunque tienen apartados comunes, hay muchas diferencias entre los readmes incluso dentro del mismo proyecto, dependiendo del autor, la plantilla que se utilice, etc. Esto hace complicado seguir las instrucciones para usar el repo. Además, el cliente recibe tamibén diferentes instrucciones.

Por un lado, deberíamos utilizar conventional commits y crear automáticamente un fichero changelog.md que va cambiando la versión en cada merge.

Por otro lado, propongo algunas modificaciones del README:
- Añadir apartado "Version and changelog" dentro de apartado "Overview" donde se indique que se revise el fichero CHANGELOG.md para ver esta info.
- Diferenciar ejecución de usuario final (normalmente con docker) de ejecución para desarrollo. Indicar los apartados que apliquen de instalación, ejecución y configuración para ambos casos. Poner el apartado pre-commit hooks como subapartado en la parte de desarrollo. Poner primero la parte de ejecución de usuario final para que sea sencillo encontrarla. 
- Añadir el uso de entornos virtuales (como opcional) donde corresponda.
- Indicar que el desarrollo es de Gradiant en algún sitio? Antes se usaba un fichero LICENSE pero no es correcto si la licencia es del cliente (y será la que él decida).
- La plantilla de README debería tener instrucciones de lo mínimo obligatorio que debe contener y se pueden poner también recomendaciones o apartados opcionales.

**Comment by apereirac** [comment]
Me he tomado algunas libertades por razones estilísticas, pero si no son aceptables las quito.

Respecto a cada punto y dónde se cubre dentro del README:
- He separado "Overview" y "Changelog and version", que tiene un link al fichero CHANGELOG.md. Me pareció mejor ponerlos como apartados independientes, ya que "Overview" lo tomo más como un descripción algo detallada del proyecto.
- Hecho. Lo he separado todo en tres secciones: información del proyecto, uso para el usuario final, y guías de desarrollo.
- Como se usa Poetry para gestionar dependencias, y es preferible trabajar con entornos virtuales, he retocado el apartado de "Requirements" y he añadido instrucciones para evitar que se cree el entorno virtual, en vez de hacerlo opcional.
- He puesto un pie de página con una frase que dice eso, y un enlace a la página de Gradiant.
- He marcado como opcional un apartado, pero no me parece que haya ningún otro que se pueda omitir.

La lista de cambios completa está en la PR.

**Comment by diegoreico** [comment]
Done in https://github.com/Gradiant/SI-AI-Data-Ops-PythonBase/pull/2
